### ISSUE TITLE
Showing its finished

### ISSUE THREAD

**Issue by dotlineX** [rahulrajpl/netizenship#1]
Hi, I loved the program, but it ends a little abruptly. Culd you add something like `print("Done!")` at the end?

**Comment by rahulrajpl** [comment]
Hey @Dotine 

Thanks for the feedback. I appreciate it. I have pushed v0.1.7 which includes your suggestion. Please upgrade the tool using `sudo pip3 install --upgrade netizenship`
Let me know your comments.

Regards,
Rahul

**Comment by dotlineX** [comment]
Thanks!
