### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by dotlineX** [rahulrajpl/netizenship#5]
For some reason bash gives me this error;

`$ sudo pip3 install netizenship`
`Collecting netizenship`
`Could not find a version that satisfies the requirement netizenship (from versions: )
No matching distribution found for netizenship
`

**Comment by rahulrajpl** [comment]
usage of pip depends on how it is configured on system. I suggest using following methods,
~~~
sudo pip install netizenship
~~~
or
~~~
python3 -m pip install netizenship
~~~
Let me know if that works, accordingly I will modify the Instructions to Install.
Thanks.

**Comment by dotlineX** [comment]
no, didn't work

**Comment by rahulrajpl** [comment]
Probably updating your pip should work
~~~
pip install --upgrade pip --user
~~~
and then
~~~
pip install netizenship
~~~

**Comment by dotlineX** [comment]
There is something wrong with my install I think. Anyways...
